-- Character names and code points generated using Python unicodedata.
local _, addon = ...
addon.characters = {
    {text = "♥", cp = 9829, name = "Heart (Black Heart Suit)", category = "Symbols"},
    {text = "¡", cp = 161, name = "Inverted Exclamation Mark", category = "Symbols", alt = "0161"},
    {text = "¢", cp = 162, name = "Cent Sign", category = "Symbols", alt = "0162"},
    {text = "£", cp = 163, name = "Pound Sign", category = "Symbols", alt = "0163"},
    {text = "¤", cp = 164, name = "Currency Sign", category = "Symbols", alt = "0164"},
    {text = "¥", cp = 165, name = "Yen Sign", category = "Symbols", alt = "0165"},
    {text = "¦", cp = 166, name = "Broken Bar", category = "Symbols", alt = "0166"},
    {text = "§", cp = 167, name = "Section Sign", category = "Symbols", alt = "0167"},
    {text = "¨", cp = 168, name = "Diaeresis", category = "Symbols", alt = "0168"},
    {text = "©", cp = 169, name = "Copyright Sign", category = "Symbols", alt = "0169"},
    {text = "ª", cp = 170, name = "Feminine Ordinal Indicator", category = "Symbols", alt = "0170"},
    {text = "«", cp = 171, name = "Left-Pointing Double Angle Quotation Mark", category = "Symbols", alt = "0171"},
    {text = "¬", cp = 172, name = "Not Sign", category = "Symbols", alt = "0172"},
    {text = "®", cp = 174, name = "Registered Sign", category = "Symbols", alt = "0174"},
    {text = "¯", cp = 175, name = "Macron", category = "Symbols", alt = "0175"},
    {text = "°", cp = 176, name = "Degree Sign", category = "Symbols", alt = "0176"},
    {text = "²", cp = 178, name = "Superscript Two", category = "Symbols", alt = "0178"},
    {text = "³", cp = 179, name = "Superscript Three", category = "Symbols", alt = "0179"},
    {text = "´", cp = 180, name = "Acute Accent", category = "Symbols", alt = "0180"},
    {text = "µ", cp = 181, name = "Micro Sign", category = "Symbols", alt = "0181"},
    {text = "¶", cp = 182, name = "Pilcrow Sign", category = "Symbols", alt = "0182"},
    {text = "·", cp = 183, name = "Middle Dot", category = "Symbols", alt = "0183"},
    {text = "¸", cp = 184, name = "Cedilla", category = "Symbols", alt = "0184"},
    {text = "¹", cp = 185, name = "Superscript One", category = "Symbols", alt = "0185"},
    {text = "º", cp = 186, name = "Masculine Ordinal Indicator", category = "Symbols", alt = "0186"},
    {text = "»", cp = 187, name = "Right-Pointing Double Angle Quotation Mark", category = "Symbols", alt = "0187"},
    {text = "¼", cp = 188, name = "Vulgar Fraction One Quarter", category = "Symbols", alt = "0188"},
    {text = "½", cp = 189, name = "Vulgar Fraction One Half", category = "Symbols", alt = "0189"},
    {text = "¾", cp = 190, name = "Vulgar Fraction Three Quarters", category = "Symbols", alt = "0190"},
    {text = "¿", cp = 191, name = "Inverted Question Mark", category = "Symbols", alt = "0191"},
    {text = "€", cp = 8364, name = "Euro Sign", category = "Symbols", alt = "0128"},
    {text = "‘", cp = 8216, name = "Left Single Quotation Mark", category = "Symbols", alt = "0145"},
    {text = "’", cp = 8217, name = "Right Single Quotation Mark", category = "Symbols", alt = "0146"},
    {text = "“", cp = 8220, name = "Left Double Quotation Mark", category = "Symbols", alt = "0147"},
    {text = "”", cp = 8221, name = "Right Double Quotation Mark", category = "Symbols", alt = "0148"},
    {text = "•", cp = 8226, name = "Bullet", category = "Symbols", alt = "0149"},
    {text = "…", cp = 8230, name = "Horizontal Ellipsis", category = "Symbols", alt = "0133"},
    {text = "†", cp = 8224, name = "Dagger", category = "Symbols", alt = "0134"},
    {text = "‡", cp = 8225, name = "Double Dagger", category = "Symbols", alt = "0135"},
    {text = "‰", cp = 8240, name = "Per Mille Sign", category = "Symbols", alt = "0137"},
    {text = "™", cp = 8482, name = "Trade Mark Sign", category = "Symbols", alt = "0153"},
    {text = "–", cp = 8211, name = "En Dash", category = "Symbols", alt = "0150"},
    {text = "—", cp = 8212, name = "Em Dash", category = "Symbols", alt = "0151"},
    {text = "♠", cp = 9824, name = "Black Spade Suit", category = "Symbols"},
    {text = "♣", cp = 9827, name = "Black Club Suit", category = "Symbols"},
    {text = "♦", cp = 9830, name = "Black Diamond Suit", category = "Symbols"},
    {text = "♪", cp = 9834, name = "Eighth Note", category = "Symbols"},
    {text = "♫", cp = 9835, name = "Beamed Eighth Notes", category = "Symbols"},
    {text = "☀", cp = 9728, name = "Black Sun With Rays", category = "Symbols"},
    {text = "☁", cp = 9729, name = "Cloud", category = "Symbols"},
    {text = "☂", cp = 9730, name = "Umbrella", category = "Symbols"},
    {text = "☃", cp = 9731, name = "Snowman", category = "Symbols"},
    {text = "★", cp = 9733, name = "Black Star", category = "Symbols"},
    {text = "☆", cp = 9734, name = "White Star", category = "Symbols"},
    {text = "✓", cp = 10003, name = "Check Mark", category = "Symbols"},
    {text = "✗", cp = 10007, name = "Ballot X", category = "Symbols"},
    {text = "✦", cp = 10022, name = "Black Four Pointed Star", category = "Symbols"},
    {text = "✧", cp = 10023, name = "White Four Pointed Star", category = "Symbols"},
    {text = "☺", cp = 9786, name = "White Smiling Face", category = "Symbols"},
    {text = "☹", cp = 9785, name = "White Frowning Face", category = "Symbols"},
    {text = "À", cp = 192, name = "Latin Capital Letter A With Grave", category = "Letters", alt = "0192"},
    {text = "Á", cp = 193, name = "Latin Capital Letter A With Acute", category = "Letters", alt = "0193"},
    {text = "Â", cp = 194, name = "Latin Capital Letter A With Circumflex", category = "Letters", alt = "0194"},
    {text = "Ã", cp = 195, name = "Latin Capital Letter A With Tilde", category = "Letters", alt = "0195"},
    {text = "Ä", cp = 196, name = "Latin Capital Letter A With Diaeresis", category = "Letters", alt = "0196"},
    {text = "Å", cp = 197, name = "Latin Capital Letter A With Ring Above", category = "Letters", alt = "0197"},
    {text = "Æ", cp = 198, name = "Latin Capital Letter Ae", category = "Letters", alt = "0198"},
    {text = "Ç", cp = 199, name = "Latin Capital Letter C With Cedilla", category = "Letters", alt = "0199"},
    {text = "È", cp = 200, name = "Latin Capital Letter E With Grave", category = "Letters", alt = "0200"},
    {text = "É", cp = 201, name = "Latin Capital Letter E With Acute", category = "Letters", alt = "0201"},
    {text = "Ê", cp = 202, name = "Latin Capital Letter E With Circumflex", category = "Letters", alt = "0202"},
    {text = "Ë", cp = 203, name = "Latin Capital Letter E With Diaeresis", category = "Letters", alt = "0203"},
    {text = "Ì", cp = 204, name = "Latin Capital Letter I With Grave", category = "Letters", alt = "0204"},
    {text = "Í", cp = 205, name = "Latin Capital Letter I With Acute", category = "Letters", alt = "0205"},
    {text = "Î", cp = 206, name = "Latin Capital Letter I With Circumflex", category = "Letters", alt = "0206"},
    {text = "Ï", cp = 207, name = "Latin Capital Letter I With Diaeresis", category = "Letters", alt = "0207"},
    {text = "Ð", cp = 208, name = "Latin Capital Letter Eth", category = "Letters", alt = "0208"},
    {text = "Ñ", cp = 209, name = "Latin Capital Letter N With Tilde", category = "Letters", alt = "0209"},
    {text = "Ò", cp = 210, name = "Latin Capital Letter O With Grave", category = "Letters", alt = "0210"},
    {text = "Ó", cp = 211, name = "Latin Capital Letter O With Acute", category = "Letters", alt = "0211"},
    {text = "Ô", cp = 212, name = "Latin Capital Letter O With Circumflex", category = "Letters", alt = "0212"},
    {text = "Õ", cp = 213, name = "Latin Capital Letter O With Tilde", category = "Letters", alt = "0213"},
    {text = "Ö", cp = 214, name = "Latin Capital Letter O With Diaeresis", category = "Letters", alt = "0214"},
    {text = "Ø", cp = 216, name = "Latin Capital Letter O With Stroke", category = "Letters", alt = "0216"},
    {text = "Ù", cp = 217, name = "Latin Capital Letter U With Grave", category = "Letters", alt = "0217"},
    {text = "Ú", cp = 218, name = "Latin Capital Letter U With Acute", category = "Letters", alt = "0218"},
    {text = "Û", cp = 219, name = "Latin Capital Letter U With Circumflex", category = "Letters", alt = "0219"},
    {text = "Ü", cp = 220, name = "Latin Capital Letter U With Diaeresis", category = "Letters", alt = "0220"},
    {text = "Ý", cp = 221, name = "Latin Capital Letter Y With Acute", category = "Letters", alt = "0221"},
    {text = "Þ", cp = 222, name = "Latin Capital Letter Thorn", category = "Letters", alt = "0222"},
    {text = "ß", cp = 223, name = "Latin Small Letter Sharp S", category = "Letters", alt = "0223"},
    {text = "à", cp = 224, name = "Latin Small Letter A With Grave", category = "Letters", alt = "0224"},
    {text = "á", cp = 225, name = "Latin Small Letter A With Acute", category = "Letters", alt = "0225"},
    {text = "â", cp = 226, name = "Latin Small Letter A With Circumflex", category = "Letters", alt = "0226"},
    {text = "ã", cp = 227, name = "Latin Small Letter A With Tilde", category = "Letters", alt = "0227"},
    {text = "ä", cp = 228, name = "Latin Small Letter A With Diaeresis", category = "Letters", alt = "0228"},
    {text = "å", cp = 229, name = "Latin Small Letter A With Ring Above", category = "Letters", alt = "0229"},
    {text = "æ", cp = 230, name = "Latin Small Letter Ae", category = "Letters", alt = "0230"},
    {text = "ç", cp = 231, name = "Latin Small Letter C With Cedilla", category = "Letters", alt = "0231"},
    {text = "è", cp = 232, name = "Latin Small Letter E With Grave", category = "Letters", alt = "0232"},
    {text = "é", cp = 233, name = "Latin Small Letter E With Acute", category = "Letters", alt = "0233"},
    {text = "ê", cp = 234, name = "Latin Small Letter E With Circumflex", category = "Letters", alt = "0234"},
    {text = "ë", cp = 235, name = "Latin Small Letter E With Diaeresis", category = "Letters", alt = "0235"},
    {text = "ì", cp = 236, name = "Latin Small Letter I With Grave", category = "Letters", alt = "0236"},
    {text = "í", cp = 237, name = "Latin Small Letter I With Acute", category = "Letters", alt = "0237"},
    {text = "î", cp = 238, name = "Latin Small Letter I With Circumflex", category = "Letters", alt = "0238"},
    {text = "ï", cp = 239, name = "Latin Small Letter I With Diaeresis", category = "Letters", alt = "0239"},
    {text = "ð", cp = 240, name = "Latin Small Letter Eth", category = "Letters", alt = "0240"},
    {text = "ñ", cp = 241, name = "Latin Small Letter N With Tilde", category = "Letters", alt = "0241"},
    {text = "ò", cp = 242, name = "Latin Small Letter O With Grave", category = "Letters", alt = "0242"},
    {text = "ó", cp = 243, name = "Latin Small Letter O With Acute", category = "Letters", alt = "0243"},
    {text = "ô", cp = 244, name = "Latin Small Letter O With Circumflex", category = "Letters", alt = "0244"},
    {text = "õ", cp = 245, name = "Latin Small Letter O With Tilde", category = "Letters", alt = "0245"},
    {text = "ö", cp = 246, name = "Latin Small Letter O With Diaeresis", category = "Letters", alt = "0246"},
    {text = "ø", cp = 248, name = "Latin Small Letter O With Stroke", category = "Letters", alt = "0248"},
    {text = "ù", cp = 249, name = "Latin Small Letter U With Grave", category = "Letters", alt = "0249"},
    {text = "ú", cp = 250, name = "Latin Small Letter U With Acute", category = "Letters", alt = "0250"},
    {text = "û", cp = 251, name = "Latin Small Letter U With Circumflex", category = "Letters", alt = "0251"},
    {text = "ü", cp = 252, name = "Latin Small Letter U With Diaeresis", category = "Letters", alt = "0252"},
    {text = "ý", cp = 253, name = "Latin Small Letter Y With Acute", category = "Letters", alt = "0253"},
    {text = "þ", cp = 254, name = "Latin Small Letter Thorn", category = "Letters", alt = "0254"},
    {text = "ÿ", cp = 255, name = "Latin Small Letter Y With Diaeresis", category = "Letters", alt = "0255"},
    {text = "Ā", cp = 256, name = "Latin Capital Letter A With Macron", category = "Letters"},
    {text = "ā", cp = 257, name = "Latin Small Letter A With Macron", category = "Letters"},
    {text = "Ă", cp = 258, name = "Latin Capital Letter A With Breve", category = "Letters"},
    {text = "ă", cp = 259, name = "Latin Small Letter A With Breve", category = "Letters"},
    {text = "Ą", cp = 260, name = "Latin Capital Letter A With Ogonek", category = "Letters"},
    {text = "ą", cp = 261, name = "Latin Small Letter A With Ogonek", category = "Letters"},
    {text = "Ć", cp = 262, name = "Latin Capital Letter C With Acute", category = "Letters"},
    {text = "ć", cp = 263, name = "Latin Small Letter C With Acute", category = "Letters"},
    {text = "Ĉ", cp = 264, name = "Latin Capital Letter C With Circumflex", category = "Letters"},
    {text = "ĉ", cp = 265, name = "Latin Small Letter C With Circumflex", category = "Letters"},
    {text = "Ċ", cp = 266, name = "Latin Capital Letter C With Dot Above", category = "Letters"},
    {text = "ċ", cp = 267, name = "Latin Small Letter C With Dot Above", category = "Letters"},
    {text = "Č", cp = 268, name = "Latin Capital Letter C With Caron", category = "Letters"},
    {text = "č", cp = 269, name = "Latin Small Letter C With Caron", category = "Letters"},
    {text = "Ď", cp = 270, name = "Latin Capital Letter D With Caron", category = "Letters"},
    {text = "ď", cp = 271, name = "Latin Small Letter D With Caron", category = "Letters"},
    {text = "Đ", cp = 272, name = "Latin Capital Letter D With Stroke", category = "Letters"},
    {text = "đ", cp = 273, name = "Latin Small Letter D With Stroke", category = "Letters"},
    {text = "Ē", cp = 274, name = "Latin Capital Letter E With Macron", category = "Letters"},
    {text = "ē", cp = 275, name = "Latin Small Letter E With Macron", category = "Letters"},
    {text = "Ĕ", cp = 276, name = "Latin Capital Letter E With Breve", category = "Letters"},
    {text = "ĕ", cp = 277, name = "Latin Small Letter E With Breve", category = "Letters"},
    {text = "Ė", cp = 278, name = "Latin Capital Letter E With Dot Above", category = "Letters"},
    {text = "ė", cp = 279, name = "Latin Small Letter E With Dot Above", category = "Letters"},
    {text = "Ę", cp = 280, name = "Latin Capital Letter E With Ogonek", category = "Letters"},
    {text = "ę", cp = 281, name = "Latin Small Letter E With Ogonek", category = "Letters"},
    {text = "Ě", cp = 282, name = "Latin Capital Letter E With Caron", category = "Letters"},
    {text = "ě", cp = 283, name = "Latin Small Letter E With Caron", category = "Letters"},
    {text = "Ĝ", cp = 284, name = "Latin Capital Letter G With Circumflex", category = "Letters"},
    {text = "ĝ", cp = 285, name = "Latin Small Letter G With Circumflex", category = "Letters"},
    {text = "Ğ", cp = 286, name = "Latin Capital Letter G With Breve", category = "Letters"},
    {text = "ğ", cp = 287, name = "Latin Small Letter G With Breve", category = "Letters"},
    {text = "Ġ", cp = 288, name = "Latin Capital Letter G With Dot Above", category = "Letters"},
    {text = "ġ", cp = 289, name = "Latin Small Letter G With Dot Above", category = "Letters"},
    {text = "Ģ", cp = 290, name = "Latin Capital Letter G With Cedilla", category = "Letters"},
    {text = "ģ", cp = 291, name = "Latin Small Letter G With Cedilla", category = "Letters"},
    {text = "Ĥ", cp = 292, name = "Latin Capital Letter H With Circumflex", category = "Letters"},
    {text = "ĥ", cp = 293, name = "Latin Small Letter H With Circumflex", category = "Letters"},
    {text = "Ħ", cp = 294, name = "Latin Capital Letter H With Stroke", category = "Letters"},
    {text = "ħ", cp = 295, name = "Latin Small Letter H With Stroke", category = "Letters"},
    {text = "Ĩ", cp = 296, name = "Latin Capital Letter I With Tilde", category = "Letters"},
    {text = "ĩ", cp = 297, name = "Latin Small Letter I With Tilde", category = "Letters"},
    {text = "Ī", cp = 298, name = "Latin Capital Letter I With Macron", category = "Letters"},
    {text = "ī", cp = 299, name = "Latin Small Letter I With Macron", category = "Letters"},
    {text = "Ĭ", cp = 300, name = "Latin Capital Letter I With Breve", category = "Letters"},
    {text = "ĭ", cp = 301, name = "Latin Small Letter I With Breve", category = "Letters"},
    {text = "Į", cp = 302, name = "Latin Capital Letter I With Ogonek", category = "Letters"},
    {text = "į", cp = 303, name = "Latin Small Letter I With Ogonek", category = "Letters"},
    {text = "İ", cp = 304, name = "Latin Capital Letter I With Dot Above", category = "Letters"},
    {text = "ı", cp = 305, name = "Latin Small Letter Dotless I", category = "Letters"},
    {text = "Ĳ", cp = 306, name = "Latin Capital Ligature Ij", category = "Letters"},
    {text = "ĳ", cp = 307, name = "Latin Small Ligature Ij", category = "Letters"},
    {text = "Ĵ", cp = 308, name = "Latin Capital Letter J With Circumflex", category = "Letters"},
    {text = "ĵ", cp = 309, name = "Latin Small Letter J With Circumflex", category = "Letters"},
    {text = "Ķ", cp = 310, name = "Latin Capital Letter K With Cedilla", category = "Letters"},
    {text = "ķ", cp = 311, name = "Latin Small Letter K With Cedilla", category = "Letters"},
    {text = "ĸ", cp = 312, name = "Latin Small Letter Kra", category = "Letters"},
    {text = "Ĺ", cp = 313, name = "Latin Capital Letter L With Acute", category = "Letters"},
    {text = "ĺ", cp = 314, name = "Latin Small Letter L With Acute", category = "Letters"},
    {text = "Ļ", cp = 315, name = "Latin Capital Letter L With Cedilla", category = "Letters"},
    {text = "ļ", cp = 316, name = "Latin Small Letter L With Cedilla", category = "Letters"},
    {text = "Ľ", cp = 317, name = "Latin Capital Letter L With Caron", category = "Letters"},
    {text = "ľ", cp = 318, name = "Latin Small Letter L With Caron", category = "Letters"},
    {text = "Ŀ", cp = 319, name = "Latin Capital Letter L With Middle Dot", category = "Letters"},
    {text = "ŀ", cp = 320, name = "Latin Small Letter L With Middle Dot", category = "Letters"},
    {text = "Ł", cp = 321, name = "Latin Capital Letter L With Stroke", category = "Letters"},
    {text = "ł", cp = 322, name = "Latin Small Letter L With Stroke", category = "Letters"},
    {text = "Ń", cp = 323, name = "Latin Capital Letter N With Acute", category = "Letters"},
    {text = "ń", cp = 324, name = "Latin Small Letter N With Acute", category = "Letters"},
    {text = "Ņ", cp = 325, name = "Latin Capital Letter N With Cedilla", category = "Letters"},
    {text = "ņ", cp = 326, name = "Latin Small Letter N With Cedilla", category = "Letters"},
    {text = "Ň", cp = 327, name = "Latin Capital Letter N With Caron", category = "Letters"},
    {text = "ň", cp = 328, name = "Latin Small Letter N With Caron", category = "Letters"},
    {text = "ŉ", cp = 329, name = "Latin Small Letter N Preceded By Apostrophe", category = "Letters"},
    {text = "Ŋ", cp = 330, name = "Latin Capital Letter Eng", category = "Letters"},
    {text = "ŋ", cp = 331, name = "Latin Small Letter Eng", category = "Letters"},
    {text = "Ō", cp = 332, name = "Latin Capital Letter O With Macron", category = "Letters"},
    {text = "ō", cp = 333, name = "Latin Small Letter O With Macron", category = "Letters"},
    {text = "Ŏ", cp = 334, name = "Latin Capital Letter O With Breve", category = "Letters"},
    {text = "ŏ", cp = 335, name = "Latin Small Letter O With Breve", category = "Letters"},
    {text = "Ő", cp = 336, name = "Latin Capital Letter O With Double Acute", category = "Letters"},
    {text = "ő", cp = 337, name = "Latin Small Letter O With Double Acute", category = "Letters"},
    {text = "Œ", cp = 338, name = "Latin Capital Ligature Oe", category = "Letters", alt = "0140"},
    {text = "œ", cp = 339, name = "Latin Small Ligature Oe", category = "Letters", alt = "0156"},
    {text = "Ŕ", cp = 340, name = "Latin Capital Letter R With Acute", category = "Letters"},
    {text = "ŕ", cp = 341, name = "Latin Small Letter R With Acute", category = "Letters"},
    {text = "Ŗ", cp = 342, name = "Latin Capital Letter R With Cedilla", category = "Letters"},
    {text = "ŗ", cp = 343, name = "Latin Small Letter R With Cedilla", category = "Letters"},
    {text = "Ř", cp = 344, name = "Latin Capital Letter R With Caron", category = "Letters"},
    {text = "ř", cp = 345, name = "Latin Small Letter R With Caron", category = "Letters"},
    {text = "Ś", cp = 346, name = "Latin Capital Letter S With Acute", category = "Letters"},
    {text = "ś", cp = 347, name = "Latin Small Letter S With Acute", category = "Letters"},
    {text = "Ŝ", cp = 348, name = "Latin Capital Letter S With Circumflex", category = "Letters"},
    {text = "ŝ", cp = 349, name = "Latin Small Letter S With Circumflex", category = "Letters"},
    {text = "Ş", cp = 350, name = "Latin Capital Letter S With Cedilla", category = "Letters"},
    {text = "ş", cp = 351, name = "Latin Small Letter S With Cedilla", category = "Letters"},
    {text = "Š", cp = 352, name = "Latin Capital Letter S With Caron", category = "Letters", alt = "0138"},
    {text = "š", cp = 353, name = "Latin Small Letter S With Caron", category = "Letters", alt = "0154"},
    {text = "Ţ", cp = 354, name = "Latin Capital Letter T With Cedilla", category = "Letters"},
    {text = "ţ", cp = 355, name = "Latin Small Letter T With Cedilla", category = "Letters"},
    {text = "Ť", cp = 356, name = "Latin Capital Letter T With Caron", category = "Letters"},
    {text = "ť", cp = 357, name = "Latin Small Letter T With Caron", category = "Letters"},
    {text = "Ŧ", cp = 358, name = "Latin Capital Letter T With Stroke", category = "Letters"},
    {text = "ŧ", cp = 359, name = "Latin Small Letter T With Stroke", category = "Letters"},
    {text = "Ũ", cp = 360, name = "Latin Capital Letter U With Tilde", category = "Letters"},
    {text = "ũ", cp = 361, name = "Latin Small Letter U With Tilde", category = "Letters"},
    {text = "Ū", cp = 362, name = "Latin Capital Letter U With Macron", category = "Letters"},
    {text = "ū", cp = 363, name = "Latin Small Letter U With Macron", category = "Letters"},
    {text = "Ŭ", cp = 364, name = "Latin Capital Letter U With Breve", category = "Letters"},
    {text = "ŭ", cp = 365, name = "Latin Small Letter U With Breve", category = "Letters"},
    {text = "Ů", cp = 366, name = "Latin Capital Letter U With Ring Above", category = "Letters"},
    {text = "ů", cp = 367, name = "Latin Small Letter U With Ring Above", category = "Letters"},
    {text = "Ű", cp = 368, name = "Latin Capital Letter U With Double Acute", category = "Letters"},
    {text = "ű", cp = 369, name = "Latin Small Letter U With Double Acute", category = "Letters"},
    {text = "Ų", cp = 370, name = "Latin Capital Letter U With Ogonek", category = "Letters"},
    {text = "ų", cp = 371, name = "Latin Small Letter U With Ogonek", category = "Letters"},
    {text = "Ŵ", cp = 372, name = "Latin Capital Letter W With Circumflex", category = "Letters"},
    {text = "ŵ", cp = 373, name = "Latin Small Letter W With Circumflex", category = "Letters"},
    {text = "Ŷ", cp = 374, name = "Latin Capital Letter Y With Circumflex", category = "Letters"},
    {text = "ŷ", cp = 375, name = "Latin Small Letter Y With Circumflex", category = "Letters"},
    {text = "Ÿ", cp = 376, name = "Latin Capital Letter Y With Diaeresis", category = "Letters", alt = "0159"},
    {text = "Ź", cp = 377, name = "Latin Capital Letter Z With Acute", category = "Letters"},
    {text = "ź", cp = 378, name = "Latin Small Letter Z With Acute", category = "Letters"},
    {text = "Ż", cp = 379, name = "Latin Capital Letter Z With Dot Above", category = "Letters"},
    {text = "ż", cp = 380, name = "Latin Small Letter Z With Dot Above", category = "Letters"},
    {text = "Ž", cp = 381, name = "Latin Capital Letter Z With Caron", category = "Letters", alt = "0142"},
    {text = "ž", cp = 382, name = "Latin Small Letter Z With Caron", category = "Letters", alt = "0158"},
    {text = "ſ", cp = 383, name = "Latin Small Letter Long S", category = "Letters"},
    {text = "Α", cp = 913, name = "Greek Capital Letter Alpha", category = "Letters"},
    {text = "Β", cp = 914, name = "Greek Capital Letter Beta", category = "Letters"},
    {text = "Γ", cp = 915, name = "Greek Capital Letter Gamma", category = "Letters"},
    {text = "Δ", cp = 916, name = "Greek Capital Letter Delta", category = "Letters"},
    {text = "Ε", cp = 917, name = "Greek Capital Letter Epsilon", category = "Letters"},
    {text = "Ζ", cp = 918, name = "Greek Capital Letter Zeta", category = "Letters"},
    {text = "Η", cp = 919, name = "Greek Capital Letter Eta", category = "Letters"},
    {text = "Θ", cp = 920, name = "Greek Capital Letter Theta", category = "Letters"},
    {text = "Ι", cp = 921, name = "Greek Capital Letter Iota", category = "Letters"},
    {text = "Κ", cp = 922, name = "Greek Capital Letter Kappa", category = "Letters"},
    {text = "Λ", cp = 923, name = "Greek Capital Letter Lamda", category = "Letters"},
    {text = "Μ", cp = 924, name = "Greek Capital Letter Mu", category = "Letters"},
    {text = "Ν", cp = 925, name = "Greek Capital Letter Nu", category = "Letters"},
    {text = "Ξ", cp = 926, name = "Greek Capital Letter Xi", category = "Letters"},
    {text = "Ο", cp = 927, name = "Greek Capital Letter Omicron", category = "Letters"},
    {text = "Π", cp = 928, name = "Greek Capital Letter Pi", category = "Letters"},
    {text = "Ρ", cp = 929, name = "Greek Capital Letter Rho", category = "Letters"},
    {text = "Σ", cp = 931, name = "Greek Capital Letter Sigma", category = "Letters"},
    {text = "Τ", cp = 932, name = "Greek Capital Letter Tau", category = "Letters"},
    {text = "Υ", cp = 933, name = "Greek Capital Letter Upsilon", category = "Letters"},
    {text = "Φ", cp = 934, name = "Greek Capital Letter Phi", category = "Letters"},
    {text = "Χ", cp = 935, name = "Greek Capital Letter Chi", category = "Letters"},
    {text = "Ψ", cp = 936, name = "Greek Capital Letter Psi", category = "Letters"},
    {text = "Ω", cp = 937, name = "Greek Capital Letter Omega", category = "Letters"},
    {text = "α", cp = 945, name = "Greek Small Letter Alpha", category = "Letters"},
    {text = "β", cp = 946, name = "Greek Small Letter Beta", category = "Letters"},
    {text = "γ", cp = 947, name = "Greek Small Letter Gamma", category = "Letters"},
    {text = "δ", cp = 948, name = "Greek Small Letter Delta", category = "Letters"},
    {text = "ε", cp = 949, name = "Greek Small Letter Epsilon", category = "Letters"},
    {text = "ζ", cp = 950, name = "Greek Small Letter Zeta", category = "Letters"},
    {text = "η", cp = 951, name = "Greek Small Letter Eta", category = "Letters"},
    {text = "θ", cp = 952, name = "Greek Small Letter Theta", category = "Letters"},
    {text = "ι", cp = 953, name = "Greek Small Letter Iota", category = "Letters"},
    {text = "κ", cp = 954, name = "Greek Small Letter Kappa", category = "Letters"},
    {text = "λ", cp = 955, name = "Greek Small Letter Lamda", category = "Letters"},
    {text = "μ", cp = 956, name = "Greek Small Letter Mu", category = "Letters"},
    {text = "ν", cp = 957, name = "Greek Small Letter Nu", category = "Letters"},
    {text = "ξ", cp = 958, name = "Greek Small Letter Xi", category = "Letters"},
    {text = "ο", cp = 959, name = "Greek Small Letter Omicron", category = "Letters"},
    {text = "π", cp = 960, name = "Greek Small Letter Pi", category = "Letters"},
    {text = "ρ", cp = 961, name = "Greek Small Letter Rho", category = "Letters"},
    {text = "σ", cp = 963, name = "Greek Small Letter Sigma", category = "Letters"},
    {text = "τ", cp = 964, name = "Greek Small Letter Tau", category = "Letters"},
    {text = "υ", cp = 965, name = "Greek Small Letter Upsilon", category = "Letters"},
    {text = "φ", cp = 966, name = "Greek Small Letter Phi", category = "Letters"},
    {text = "χ", cp = 967, name = "Greek Small Letter Chi", category = "Letters"},
    {text = "ψ", cp = 968, name = "Greek Small Letter Psi", category = "Letters"},
    {text = "ω", cp = 969, name = "Greek Small Letter Omega", category = "Letters"},
    {text = "←", cp = 8592, name = "Leftwards Arrow", category = "Arrows"},
    {text = "↑", cp = 8593, name = "Upwards Arrow", category = "Arrows"},
    {text = "→", cp = 8594, name = "Rightwards Arrow", category = "Arrows"},
    {text = "↓", cp = 8595, name = "Downwards Arrow", category = "Arrows"},
    {text = "↔", cp = 8596, name = "Left Right Arrow", category = "Arrows"},
    {text = "↕", cp = 8597, name = "Up Down Arrow", category = "Arrows"},
    {text = "↖", cp = 8598, name = "North West Arrow", category = "Arrows"},
    {text = "↗", cp = 8599, name = "North East Arrow", category = "Arrows"},
    {text = "↘", cp = 8600, name = "South East Arrow", category = "Arrows"},
    {text = "↙", cp = 8601, name = "South West Arrow", category = "Arrows"},
    {text = "↩", cp = 8617, name = "Leftwards Arrow With Hook", category = "Arrows"},
    {text = "↪", cp = 8618, name = "Rightwards Arrow With Hook", category = "Arrows"},
    {text = "⇐", cp = 8656, name = "Leftwards Double Arrow", category = "Arrows"},
    {text = "⇑", cp = 8657, name = "Upwards Double Arrow", category = "Arrows"},
    {text = "⇒", cp = 8658, name = "Rightwards Double Arrow", category = "Arrows"},
    {text = "⇓", cp = 8659, name = "Downwards Double Arrow", category = "Arrows"},
    {text = "⇔", cp = 8660, name = "Left Right Double Arrow", category = "Arrows"},
    {text = "±", cp = 177, name = "Plus-Minus Sign", category = "Math", alt = "0177"},
    {text = "×", cp = 215, name = "Multiplication Sign", category = "Math", alt = "0215"},
    {text = "÷", cp = 247, name = "Division Sign", category = "Math", alt = "0247"},
    {text = "≠", cp = 8800, name = "Not Equal To", category = "Math"},
    {text = "≈", cp = 8776, name = "Almost Equal To", category = "Math"},
    {text = "≤", cp = 8804, name = "Less-Than Or Equal To", category = "Math"},
    {text = "≥", cp = 8805, name = "Greater-Than Or Equal To", category = "Math"},
    {text = "∞", cp = 8734, name = "Infinity", category = "Math"},
    {text = "√", cp = 8730, name = "Square Root", category = "Math"},
    {text = "∑", cp = 8721, name = "N-Ary Summation", category = "Math"},
    {text = "∏", cp = 8719, name = "N-Ary Product", category = "Math"},
    {text = "∆", cp = 8710, name = "Increment", category = "Math"},
    {text = "∫", cp = 8747, name = "Integral", category = "Math"},
    {text = "∂", cp = 8706, name = "Partial Differential", category = "Math"},
    {text = "∅", cp = 8709, name = "Empty Set", category = "Math"},
    {text = "∈", cp = 8712, name = "Element Of", category = "Math"},
    {text = "∉", cp = 8713, name = "Not An Element Of", category = "Math"},
    {text = "∩", cp = 8745, name = "Intersection", category = "Math"},
    {text = "∪", cp = 8746, name = "Union", category = "Math"},
    {text = "⊂", cp = 8834, name = "Subset Of", category = "Math"},
    {text = "⊃", cp = 8835, name = "Superset Of", category = "Math"},
    {text = "⊆", cp = 8838, name = "Subset Of Or Equal To", category = "Math"},
    {text = "⊇", cp = 8839, name = "Superset Of Or Equal To", category = "Math"},
    {text = "∧", cp = 8743, name = "Logical And", category = "Math"},
    {text = "∨", cp = 8744, name = "Logical Or", category = "Math"},
    {text = "{star}", code = "{star} / {rt1}", name = "Star raid marker", category = "Raid marks", display = "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_1:20|t"},
    {text = "{circle}", code = "{circle} / {rt2}", name = "Circle raid marker", category = "Raid marks", display = "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_2:20|t"},
    {text = "{diamond}", code = "{diamond} / {rt3}", name = "Diamond raid marker", category = "Raid marks", display = "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_3:20|t"},
    {text = "{triangle}", code = "{triangle} / {rt4}", name = "Triangle raid marker", category = "Raid marks", display = "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_4:20|t"},
    {text = "{moon}", code = "{moon} / {rt5}", name = "Moon raid marker", category = "Raid marks", display = "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_5:20|t"},
    {text = "{square}", code = "{square} / {rt6}", name = "Square raid marker", category = "Raid marks", display = "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_6:20|t"},
    {text = "{cross}", code = "{cross} / {rt7}", name = "Cross raid marker", category = "Raid marks", display = "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_7:20|t"},
    {text = "{skull}", code = "{skull} / {rt8}", name = "Skull raid marker", category = "Raid marks", display = "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_8:20|t"},
}
